# Generated by Django 3.1.6 on 2021-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210706_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='Election_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='show_result',
            field=models.BooleanField(default=False),
        ),
    ]
